version: "3.8"

services:
  # Node.js application
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/myappdb
    networks:
      - myapp-network

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - myapp-network

# Define a network
networks:
  myapp-network:
    driver: bridge

# Volumes to persist MongoDB data
volumes:
  mongo_data:
    driver: local
